# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160530_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
        migrations.AddField(
            model_name='member',
            name='picture_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
